input InspectionItemInput {
  deviceId: ID!
  isSuccess: Boolean!
}

type InspectionPoolItem {
  id: ID!
  name: String!
  model: String!
  serialNumber: String!
  lastInspectionDate: String
  validUntil: String! # Дата планового следующего обхода
  isOverdue: Boolean!
  controlType: String!
}

type InspectionPoolResponse {
  items: [InspectionPoolItem!]!
  totalCount: Int!
  yearlySummary: [MonthlySummary!]!
}

type InspectedDeviceLink {
  id: ID! # Это id самой строки связи (link.id из Postgres)
  deviceStatus: String! # 'returned' (Годен) или 'dismantled' (Брак)
  device: Device! # Внутри лежит полноценный исходный тип прибора со своим чистым UUID
}

# 2. Обновляем тип элемента архива
type InspectionBatchItem {
  id: ID!
  number: String!
  date: String!
  comment: String
  # Переходим со списка приборов на список связей
  devicesToBatches: [InspectedDeviceLink!]!
}

type InspectionArchiveResponse {
  items: [InspectionBatchItem!]!
  totalCount: Int!
}

extend type Query {
  getInspectionPoolByMonth(
    targetMonth: String!
    limit: Int!
    offset: Int!
  ): InspectionPoolResponse!

  getInspectionBatchesArchive(
    limit: Int!
    offset: Int!
    year: Int!
  ): InspectionArchiveResponse!
}

extend type Mutation {
  createBulkInspection(
    items: [InspectionItemInput!]!
    intervalMonths: Int!
  ): Boolean!
}
